.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/atlas.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/atlas.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/fontResource\&.h'\fP
.br
\fC#include 'lightsky/draw/texture\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/atlas_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBls::draw::atlasEntry\fP"
.br
.RI "\fI\fBatlasEntry\fP \fP"
.ti -1c
.RI "class \fBls::draw::atlas\fP"
.br
.RI "\fITexture Atlas Class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
