.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/bits.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/bits.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <climits>\fP
.br
\fC#include 'lightsky/utils/assert\&.h'\fP
.br
\fC#include 'lightsky/utils/generic/bits_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBls::utils::bitMask\fP"
.br
.RI "\fI\fBbitMask\fP Convenience structure to facilitate bit acquisition of bytes\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLS_BITS_PER_BYTE\fP   CHAR_BIT"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename key_t > constexpr const bitMask * \fBls::utils::getByte\fP (const key_t *key, unsigned iter)"
.br
.RI "\fIgetByte Retrieve the Nth byte of a basic data type\&. \fP"
.ti -1c
.RI "template<> constexpr const bitMask * \fBls::utils::getByte\fP (const char *key, unsigned iter)"
.br
.RI "\fIgetByte (char string specialization) Retrieve the Nth byte of a basic data type\&. \fP"
.ti -1c
.RI "template<> constexpr const bitMask * \fBls::utils::getByte\fP (const wchar_t *key, unsigned iter)"
.br
.RI "\fIgetByte (wchar_t string specialization) Retrieve the Nth byte of a basic data type\&. \fP"
.ti -1c
.RI "template<> constexpr const bitMask * \fBls::utils::getByte\fP (const char16_t *key, unsigned iter)"
.br
.RI "\fIgetByte (char16_t string specialization) Retrieve the Nth byte of a basic data type\&. \fP"
.ti -1c
.RI "template<> constexpr const bitMask * \fBls::utils::getByte\fP (const char32_t *key, unsigned iter)"
.br
.RI "\fIgetByte (char32_t string specialization) Retrieve the Nth byte of a basic data type\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LS_BITS_PER_BYTE   CHAR_BIT"

.PP
Definition at line 16 of file bits\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
