.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/blendObject.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/blendObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/color\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/blendObject_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::blendObject\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum : int { \fBls::draw::LS_BLEND\fP = GL_BLEND }"
.br
.ti -1c
.RI "enum \fBls::draw::blend_color_t\fP : int { \fBls::draw::LS_BLEND_COLOR\fP = GL_BLEND_COLOR }"
.br
.ti -1c
.RI "enum \fBls::draw::blend_equ_t\fP : int { \fBls::draw::LS_BLEND_ADD\fP = GL_FUNC_ADD, \fBls::draw::LS_BLEND_SUB\fP = GL_FUNC_SUBTRACT, \fBls::draw::LS_BLEND_REV_SUB\fP = GL_FUNC_REVERSE_SUBTRACT, \fBls::draw::LS_BLEND_MIN\fP = GL_MIN, \fBls::draw::LS_BLEND_MAX\fP = GL_MAX, \fBls::draw::LS_DEFAULT_BLEND_EQU\fP = GL_FUNC_ADD }"
.br
.ti -1c
.RI "enum \fBls::draw::blend_equ_color_t\fP : int { \fBls::draw::LS_BLEND_EQUATION_RGB\fP = GL_BLEND_EQUATION_RGB, \fBls::draw::LS_BLEND_EQUATION_ALPHA\fP = GL_BLEND_EQUATION_ALPHA }"
.br
.ti -1c
.RI "enum \fBls::draw::blend_func_t\fP : int { \fBls::draw::LS_ZERO\fP = GL_ZERO, \fBls::draw::LS_ONE\fP = GL_ONE, \fBls::draw::LS_SRC_COLOR\fP = GL_SRC_COLOR, \fBls::draw::LS_ONE_MINUS_SRC_COLOR\fP = GL_ONE_MINUS_SRC_COLOR, \fBls::draw::LS_DST_COLOR\fP = GL_DST_COLOR, \fBls::draw::LS_ONE_MINUS_DST_COLOR\fP = GL_ONE_MINUS_DST_COLOR, \fBls::draw::LS_SRC_ALPHA\fP = GL_SRC_ALPHA, \fBls::draw::LS_ONE_MINUS_SRC_ALPHA\fP = GL_ONE_MINUS_SRC_ALPHA, \fBls::draw::LS_DST_ALPHA\fP = GL_DST_ALPHA, \fBls::draw::LS_ONE_MINUS_DST_ALPHA\fP = GL_ONE_MINUS_DST_ALPHA, \fBls::draw::LS_CONST_COLOR\fP = GL_CONSTANT_COLOR, \fBls::draw::LS_ONE_MINUS_CONST_COLOR\fP = GL_ONE_MINUS_CONSTANT_COLOR, \fBls::draw::LS_CONST_ALPHA\fP = GL_CONSTANT_ALPHA, \fBls::draw::LS_ONE_MINUS_CONST_ALPHA\fP = GL_ONE_MINUS_CONSTANT_ALPHA }"
.br
.ti -1c
.RI "enum \fBls::draw::blend_func_color_t\fP : int { \fBls::draw::LS_BLEND_SRC_RGB\fP = GL_BLEND_SRC_RGB, \fBls::draw::LS_BLEND_DST_RGB\fP = GL_BLEND_DST_RGB, \fBls::draw::LS_BLEND_SRC_ALPHA\fP = GL_BLEND_SRC_ALPHA, \fBls::draw::LS_BLEND_DST_ALPHA\fP = GL_BLEND_DST_ALPHA }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
