.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/byteSize.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/byteSize.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/utils/generic/byteSize_impl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr unsigned \fBls::utils::getArgByteSize\fP (unsigned size)"
.br
.RI "\fIgetArgByteSize Helper function to sum the number of bytes used by a set of types\&. \fP"
.ti -1c
.RI "template<typename\&.\&.\&. integral_t> constexpr unsigned \fBls::utils::getArgByteSize\fP (unsigned size, integral_t\&.\&.\&.sizeN)"
.br
.RI "\fIgetArgByteSize Helper function to sum the number of bytes used by a set of types\&. \fP"
.ti -1c
.RI "template<typename\&.\&.\&. integral_t> constexpr unsigned \fBls::utils::getByteSize\fP ()"
.br
.RI "\fIgetByteSize Sum the number of bytes used by a set of types\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
