.TH "C:/Users/miles/C++/projects/LightSky/lightsky/script Directory Reference" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/script Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgeneric\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfactory\&.h\fP"
.br
.ti -1c
.RI "file \fBfunctor\&.h\fP"
.br
.ti -1c
.RI "file \fBscript\&.h\fP"
.br
.ti -1c
.RI "file \fBscriptable\&.h\fP"
.br
.ti -1c
.RI "file \fBsetup\&.h\fP"
.br
.ti -1c
.RI "file \fBvariable\&.h\fP"
.br
.in -1c
