.TH "C:/Users/miles/C++/projects/LightSky/lightsky/math Directory Reference" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/math Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgeneric\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfixed\&.h\fP"
.br
.ti -1c
.RI "file \fBmat2\&.h\fP"
.br
.ti -1c
.RI "file \fBmat3\&.h\fP"
.br
.ti -1c
.RI "file \fBmat4\&.h\fP"
.br
.ti -1c
.RI "file \fBmat_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBmath\&.h\fP"
.br
.ti -1c
.RI "file \fBperlinNoise\&.h\fP"
.br
.ti -1c
.RI "file \fBquat\&.h\fP"
.br
.ti -1c
.RI "file \fBquat_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBscalar_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBsetup\&.h\fP"
.br
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.ti -1c
.RI "file \fBvec2\&.h\fP"
.br
.ti -1c
.RI "file \fBvec3\&.h\fP"
.br
.ti -1c
.RI "file \fBvec4\&.h\fP"
.br
.ti -1c
.RI "file \fBvec_utils\&.h\fP"
.br
.in -1c
