.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/dataResource.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/dataResource.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'lightsky/utils/setup\&.h'\fP
.br
\fC#include 'lightsky/utils/resource\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::utils::dataResource\fP"
.br
.RI "\fIBasic memory object/file abstraction\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
