.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/depthObject.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/depthObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/color\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/depthObject_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::depthObject\fP"
.br
.RI "\fIRender Depth Manipulation Object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::compare_func_t\fP : int { \fBls::draw::LS_DEPTH_ALWAYS\fP = GL_ALWAYS, \fBls::draw::LS_DEPTH_NEVER\fP = GL_NEVER, \fBls::draw::LS_DEPTH_LESS\fP = GL_LESS, \fBls::draw::LS_DEPTH_EQUAL\fP = GL_EQUAL, \fBls::draw::LS_DEPTH_LEQUAL\fP = GL_LEQUAL, \fBls::draw::LS_DEPTH_GEQUAL\fP = GL_GEQUAL, \fBls::draw::LS_DEPTH_NEQUAL\fP = GL_NOTEQUAL }"
.br
.RI "\fIDepth Comparison Operations\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
