.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/display.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/display.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/display_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::display\fP"
.br
.RI "\fIDisplay Class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::fullscreen_t\fP : int { \fBls::draw::FULLSCREEN_DISPLAY\fP, \fBls::draw::FULLSCREEN_WINDOW\fP, \fBls::draw::FULLSCREEN_DEFAULT\fP = FULLSCREEN_DISPLAY }"
.br
.RI "\fIFull-Screen Flags\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
