.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/src/display.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/src/display.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <SDL2/SDL_hints\&.h>\fP
.br
\fC#include <SDL2/SDL_video\&.h>\fP
.br
\fC#include <SDL2/SDL_render\&.h>\fP
.br
\fC#include 'lightsky/draw/color\&.h'\fP
.br
\fC#include 'lightsky/draw/display\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBls::draw::printWindowFlags\fP (uint32_t flags)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
