.TH "C:/Users/miles/C++/projects/LightSky/lightsky/script/factory.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/script/factory.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/script/setup\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::script\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "variable * \fBls::script::createScriptVar\fP (hash_t)"
.br
.ti -1c
.RI "functor * \fBls::script::createScriptFunc\fP (hash_t)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
