.TH "C:/Users/miles/C++/projects/LightSky/lightsky/math/src/fixed.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/math/src/fixed.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/math/types\&.h'\fP
.br
\fC#include 'lightsky/math/fixed\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::math\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int32_t, 7)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int32_t, 15)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int32_t, 23)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int64_t, 15)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int64_t, 31)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, int64_t, 47)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint32_t, 8)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint32_t, 16)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint32_t, 24)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint64_t, 16)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint64_t, 32)"
.br
.ti -1c
.RI "\fBls::math::LS_DEFINE_CLASS_TYPE\fP (fixed_t, uint64_t, 48)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
