.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/fontResource.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/fontResource.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/utils/resource\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/fontResource_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBls::draw::glyph\fP"
.br
.RI "\fIFont Metrics\&. \fP"
.ti -1c
.RI "class \fBls::draw::fontResource\fP"
.br
.RI "\fIFont File loader\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
