.TH "C:/Users/miles/C++/projects/LightSky/lightsky/game/gameState.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/game/gameState.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/game/system\&.h'\fP
.br
\fC#include 'lightsky/game/generic/gameState_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::game::gameState\fP"
.br
.RI "\fIGame State Base Class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::game\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::game::game_state_t\fP : unsigned { \fBls::game::LS_GAME_INVALID\fP = (unsigned)-1, \fBls::game::LS_GAME_PAUSED\fP = 0, \fBls::game::LS_GAME_RUNNING\fP = 1, \fBls::game::LS_GAME_STOPPED\fP = 2, \fBls::game::LS_GAME_INIT\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
