.TH "C:/Users/miles/C++/projects/LightSky/lightsky/game/game.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/game/game.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/game/setup\&.h'\fP
.br
\fC#include 'lightsky/game/gameState\&.h'\fP
.br
\fC#include 'lightsky/game/manager\&.h'\fP
.br
\fC#include 'lightsky/game/system\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::game\fP"
.br
.ti -1c
.RI " \fBls::game::global\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBls::game::global::init\fP ()"
.br
.RI "\fILightSky Initialization\&. \fP"
.ti -1c
.RI "void \fBls::game::global::terminate\fP ()"
.br
.RI "\fILightSky termination\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
