.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/geometry.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/geometry.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/setup\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.ti -1c
.RI " \fBls::draw::geometry\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "math::vec3 \fBls::draw::geometry::calcNormal\fP (const math::vec3 &v0, const math::vec3 &v1, const math::vec3 &v2)"
.br
.ti -1c
.RI "void \fBls::draw::geometry::calcTangents\fP (unsigned vertCount, const math::vec3 *const positions, const math::vec2 *const uvs, math::vec3 *tangents, math::vec3 *bitangents)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
