.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/imageResource.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/imageResource.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/utils/resource\&.h'\fP
.br
\fC#include 'lightsky/draw/color\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/imageResource_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::imageResource\fP"
.br
.RI "\fIA resource object to load image files\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::img_file_t\fP { \fBls::draw::img_file_t::IMG_FILE_BMP\fP, \fBls::draw::img_file_t::IMG_FILE_EXR\fP, \fBls::draw::img_file_t::IMG_FILE_GIF\fP, \fBls::draw::img_file_t::IMG_FILE_HDR\fP, \fBls::draw::img_file_t::IMG_FILE_ICO\fP, \fBls::draw::img_file_t::IMG_FILE_JPG\fP, \fBls::draw::img_file_t::IMG_FILE_J2K\fP, \fBls::draw::img_file_t::IMG_FILE_PNG\fP, \fBls::draw::img_file_t::IMG_FILE_PPM\fP, \fBls::draw::img_file_t::IMG_FILE_TGA\fP, \fBls::draw::img_file_t::IMG_FILE_TIF\fP, \fBls::draw::img_file_t::IMG_FILE_WBP\fP, \fBls::draw::img_file_t::IMG_FILE_XPM\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
