.TH "C:/Users/miles/C++/projects/LightSky/lightsky/lightsky.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/lightsky.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/setup/setup\&.h'\fP
.br
\fC#include 'lightsky/utils/utils\&.h'\fP
.br
\fC#include 'lightsky/math/math\&.h'\fP
.br
\fC#include 'lightsky/draw/draw\&.h'\fP
.br
\fC#include 'lightsky/script/script\&.h'\fP
.br
\fC#include 'lightsky/game/game\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
