.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/log.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/log.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'lightsky/utils/generic/log_impl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename arg_t > void \fBls::utils::logMsg\fP (const arg_t &arg)"
.br
.RI "\fIPrint multiple parameters to std::cout\&. \fP"
.ti -1c
.RI "template<typename arg_t , typename\&.\&.\&. args_t> void \fBls::utils::logMsg\fP (const arg_t &arg, const args_t &\&.\&.\&.args)"
.br
.RI "\fIPrint multiple parameters to std::cout\&. \fP"
.ti -1c
.RI "template<typename arg_t > void \fBls::utils::logErr\fP (const arg_t &arg)"
.br
.RI "\fIPrint multiple parameters to std::cerr\&. \fP"
.ti -1c
.RI "template<typename arg_t , typename\&.\&.\&. args_t> void \fBls::utils::logErr\fP (const arg_t &arg, const args_t &\&.\&.\&.args)"
.br
.RI "\fIPrint multiple parameters to std::cerr\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
