.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/generic/log_impl.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/generic/log_impl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Arg > void \fBls::utils::logMsg\fP (const Arg &arg)"
.br
.ti -1c
.RI "template<typename Arg , typename\&.\&.\&. Args> void \fBls::utils::logMsg\fP (const Arg &arg, const Args &\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename Arg > void \fBls::utils::logErr\fP (const Arg &arg)"
.br
.ti -1c
.RI "template<typename Arg , typename\&.\&.\&. Args> void \fBls::utils::logErr\fP (const Arg &arg, const Args &\&.\&.\&.args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
