.TH "ls" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdraw\fP"
.br
.ti -1c
.RI " \fBgame\fP"
.br
.ti -1c
.RI " \fBmath\fP"
.br
.ti -1c
.RI " \fBscript\fP"
.br
.ti -1c
.RI " \fButils\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fButils/log\&.h\fP
.PP
This file contains wrappers around std::cout and std::cerr\&. It's just a simple way to clean up some of the syntax when writing to a standard output stream\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
