.TH "ls::draw::atlasEntry" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::atlasEntry \- 
.PP
\fBatlasEntry\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <atlas\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "math::vec2 \fBsize\fP"
.br
.ti -1c
.RI "math::vec2 \fBadvance\fP"
.br
.ti -1c
.RI "math::vec2 \fBbearing\fP"
.br
.ti -1c
.RI "math::vec2 \fBuv\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBatlasEntry\fP 


.PP
 An \fBatlasEntry\fP contains the coordinates of individual glyphs within a texture 
.SS "atlas\&. "

.PP
Definition at line 23 of file atlas\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "math::vec2 ls::draw::atlasEntry::advance"
Advance is mostly used for font kerning 
.PP
Definition at line 32 of file atlas\&.h\&.
.SS "math::vec2 ls::draw::atlasEntry::bearing"
Bearing is mostly used for font kerning\&. 
.PP
Definition at line 37 of file atlas\&.h\&.
.SS "math::vec2 ls::draw::atlasEntry::size"
Size corresponds to the vertex width and height of a glyph\&. 
.PP
Definition at line 27 of file atlas\&.h\&.
.SS "math::vec2 ls::draw::atlasEntry::uv[2]"
UV is an array representing the top-left and bottom-right portions of a glyph (an element in a texture atlas)\&. 
.PP
Definition at line 43 of file atlas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
