.TH "ls::draw::meshResource" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::meshResource \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <meshResource\&.h>\fP
.PP
Inherits \fBls::utils::resource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmeshResource\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBmeshResource\fP (const \fBmeshResource\fP &)=delete"
.br
.RI "\fICopy Constructor -- DELETED\&. \fP"
.ti -1c
.RI "\fBmeshResource\fP (\fBmeshResource\fP &&mr)"
.br
.RI "\fIMove Constructor\&. \fP"
.ti -1c
.RI "virtual \fB~meshResource\fP () override"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "\fBmeshResource\fP & \fBoperator=\fP (const \fBmeshResource\fP &)=delete"
.br
.RI "\fICopy Constructor -- DELETED\&. \fP"
.ti -1c
.RI "\fBmeshResource\fP & \fBoperator=\fP (\fBmeshResource\fP &&mr)"
.br
.RI "\fIMove Operator\&. \fP"
.ti -1c
.RI "unsigned \fBgetNumVertices\fP () const "
.br
.ti -1c
.RI "\fBvertex\fP * \fBgetVertices\fP () const "
.br
.ti -1c
.RI "virtual void \fBunload\fP () override"
.br
.RI "\fIUnload\&. \fP"
.ti -1c
.RI "bool \fBloadFile\fP (const std::string &filename) override"
.br
.RI "\fILoad a 3D mesh file -- NOT YET IMPLEMENTED\&. \fP"
.ti -1c
.RI "virtual bool \fBsaveFile\fP (const std::string &) const override"
.br
.RI "\fISave a mesh to a file -- NOT YET IMPLEMENTED\&. \fP"
.ti -1c
.RI "\fBdraw_mode_t\fP \fBgetDrawMode\fP () const "
.br
.ti -1c
.RI "const \fBboundingBox\fP & \fBgetBoundingBox\fP () const "
.br
.ti -1c
.RI "bool \fBloadPolygon\fP (unsigned numPoints=3)"
.br
.ti -1c
.RI "bool \fBloadTriangle\fP ()"
.br
.ti -1c
.RI "bool \fBloadQuad\fP ()"
.br
.ti -1c
.RI "bool \fBloadCircle\fP (unsigned numPoints=5)"
.br
.ti -1c
.RI "bool \fBloadCube\fP ()"
.br
.ti -1c
.RI "bool \fBloadCylinder\fP (unsigned numSides=2)"
.br
.ti -1c
.RI "bool \fBloadCone\fP (unsigned numSides=2)"
.br
.ti -1c
.RI "bool \fBloadSphere\fP (unsigned resolution)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The mesh resource can be used to load a mesh or meshes from a file\&. It can also be used to generate basic primitives such as a sphere, cube, cone, etc\&. 
.PP
Definition at line 26 of file meshResource\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ls::draw::meshResource::meshResource ()"

.PP
Constructor\&. Initializes all members contained within *this\&. 
.PP
Definition at line 29 of file meshResource\&.cpp\&.
.SS "ls::draw::meshResource::meshResource (const \fBmeshResource\fP &)\fC [delete]\fP"

.PP
Copy Constructor -- DELETED\&. 
.SS "ls::draw::meshResource::meshResource (\fBmeshResource\fP &&mr)"

.PP
Move Constructor\&. Moves all data from the input parameter into *this\&. No copies are performed during the operation\&.
.PP
\fBParameters:\fP
.RS 4
\fImr\fP An r-value reference to a temporary mesh resource object\&. 
.RE
.PP

.PP
Definition at line 35 of file meshResource\&.cpp\&.
.SS "ls::draw::meshResource::~meshResource ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Destructor\&. Unloads all data contain within *this\&. 
.PP
Definition at line 22 of file meshResource\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBboundingBox\fP & ls::draw::meshResource::getBoundingBox () const\fC [inline]\fP"
Get the maximum bounds of a loaded mesh\&.
.PP
\fBReturns:\fP
.RS 4
A constant reference to an \fBboundingBox\fP object\&. 
.RE
.PP

.PP
Definition at line 29 of file meshResource_impl\&.h\&.
.SS "\fBdraw_mode_t\fP ls::draw::meshResource::getDrawMode () const\fC [inline]\fP"
Get the draw mode that was generated while loading a mesh\&.
.PP
\fBReturns:\fP
.RS 4
The target draw mode for the currently loaded mesh\&. 
.RE
.PP

.PP
Definition at line 22 of file meshResource_impl\&.h\&.
.SS "unsigned ls::draw::meshResource::getNumVertices () const\fC [inline]\fP"
Get the number of loaded vertex variables in a mesh\&.
.PP
\fBReturns:\fP
.RS 4
An unsigned integral type, representing the number of vertices contained within the mesh loaded by *this\&. 
.RE
.PP

.PP
Definition at line 8 of file meshResource_impl\&.h\&.
.SS "\fBvertex\fP * ls::draw::meshResource::getVertices () const\fC [inline]\fP"
Get the array of standard vertex types of a loaded mesh\&.
.PP
\fBReturns:\fP
.RS 4
A pointer to the internal array which contains the vertices loaded by *this\&. 
.RE
.PP

.PP
Definition at line 15 of file meshResource_impl\&.h\&.
.SS "bool ls::draw::meshResource::loadCircle (unsignednumPoints = \fC5\fP)\fC [inline]\fP"
Load a set of vertices representing a circle\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 43 of file meshResource_impl\&.h\&.
.SS "bool ls::draw::meshResource::loadCone (unsignednumSides = \fC2\fP)"
Load a set of vertices representing a cone\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 415 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadCube ()"
Load a set of vertices representing a cube\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 203 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadCylinder (unsignednumSides = \fC2\fP)"
Load a set of vertices representing a cylinder\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 334 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadFile (const std::string &filename)\fC [override]\fP, \fC [virtual]\fP"

.PP
Load a 3D mesh file -- NOT YET IMPLEMENTED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP A string object containing the relative path name to a file that should be loadable into memory\&.
.RE
.PP
\fBReturns:\fP
.RS 4
true if the file was successfully loaded\&. False if not\&. 
.RE
.PP

.PP
Implements \fBls::utils::resource\fP\&.
.PP
Definition at line 120 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadPolygon (unsignednumPoints = \fC3\fP)"
N-Sided polygon primitive loading method
.PP
\fBParameters:\fP
.RS 4
\fInumPoints\fP The number of points that the polygon should contain\&. This number must be greater than 1\&.
.RE
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 170 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadQuad ()"
Load a set of vertices representing a square/quad\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 135 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadSphere (unsignedresolution)"
Load a set of vertices representing a sphere\&.
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&. 
.RE
.PP

.PP
Definition at line 487 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::loadTriangle ()\fC [inline]\fP"
Triangle primitive loading method
.PP
\fBReturns:\fP
.RS 4
TRUE if the function loaded the mesh correctly, or FALSE if an error occurred during the load\&.
.RE
.PP
Triangle texture coordinates are as follows:
.PP
|----1---| | /\\ | | / \\ | | / \\ | 0/______\\2 
.PP
Definition at line 36 of file meshResource_impl\&.h\&.
.SS "\fBmeshResource\fP& ls::draw::meshResource::operator= (const \fBmeshResource\fP &)\fC [delete]\fP"

.PP
Copy Constructor -- DELETED\&. 
.SS "\fBmeshResource\fP & ls::draw::meshResource::operator= (\fBmeshResource\fP &&mr)"

.PP
Move Operator\&. Moves all data from the input parameter into *this\&. No copies are performed during the operation\&.
.PP
\fBParameters:\fP
.RS 4
\fImr\fP An r-value reference to a temporary mesh resource object\&.
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to *this\&. 
.RE
.PP

.PP
Definition at line 55 of file meshResource\&.cpp\&.
.SS "bool ls::draw::meshResource::saveFile (const std::string &) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Save a mesh to a file -- NOT YET IMPLEMENTED\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP A string object containing the relative path name to a file that should be saved to the computer\&.
.RE
.PP
\fBReturns:\fP
.RS 4
true if the file was successfully saved\&. False if not\&. 
.RE
.PP

.PP
Implements \fBls::utils::resource\fP\&.
.PP
Definition at line 128 of file meshResource\&.cpp\&.
.SS "void ls::draw::meshResource::unload ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Unload\&. Free all memory used by *this\&. 
.PP
Implements \fBls::utils::resource\fP\&.
.PP
Definition at line 79 of file meshResource\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
