.TH "ls::draw::renderer" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::renderer \- 
.PP
Renderer Object On desktop platforms, this object strictly represents an OpenGL 3\&.3 context\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <renderer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetViewport\fP (const math::vec2i &pos, const math::vec2i &size)"
.br
.ti -1c
.RI "void \fBsetWindingOrder\fP (\fBwinding_order_t\fP wo)"
.br
.ti -1c
.RI "\fBwinding_order_t\fP \fBgetWindingOrder\fP () const "
.br
.ti -1c
.RI "void \fBsetFaceCulling\fP (bool shouldCull)"
.br
.ti -1c
.RI "bool \fBgetFaceCulling\fP () const "
.br
.ti -1c
.RI "void \fBsetDepthTesting\fP (bool dt)"
.br
.ti -1c
.RI "bool \fBgetDepthTesting\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Renderer Object On desktop platforms, this object strictly represents an OpenGL 3\&.3 context\&. 


.PP
 
.SS "Only state-specific options are kept within this object\&. "

.PP
Definition at line 79 of file renderer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ls::draw::renderer::getDepthTesting () const\fC [inline]\fP"
Determine if depth testing is enabled for all rendered polygons\&.
.PP
\fBReturns:\fP
.RS 4
a boolean flag which can be used to determine if depth testing is enabled (if TRUE) or disabled\&. 
.RE
.PP

.PP
Definition at line 57 of file renderer_impl\&.h\&.
.SS "bool ls::draw::renderer::getFaceCulling () const\fC [inline]\fP"
Get a boolean flag which tells if the current renderer is culling polygon faces or not\&.
.PP
\fBReturns:\fP
.RS 4
a boolean flag that determines whether the renderer is culling polygon faces or not\&. 
.RE
.PP

.PP
Definition at line 40 of file renderer_impl\&.h\&.
.SS "\fBwinding_order_t\fP ls::draw::renderer::getWindingOrder () const\fC [inline]\fP"
Retrieve the current winding order of rendered polygons\&.
.PP
\fBReturns:\fP
.RS 4
An enumeration of winding_order_t, indicating whether polygons are to be rendered with their front faces as clockwise or counter- clockwise\&. 
.RE
.PP

.PP
Definition at line 23 of file renderer_impl\&.h\&.
.SS "void ls::draw::renderer::setDepthTesting (booldt)\fC [inline]\fP"
Enable depth testing of rendered polygons\&. Depth testing can be used to render close polygons in front of distant ones\&.
.PP
\fBParameters:\fP
.RS 4
\fIdt\fP A boolean flag which can be used to enable depth testing (if TRUE) or disable it\&. 
.RE
.PP

.PP
Definition at line 50 of file renderer_impl\&.h\&.
.SS "void ls::draw::renderer::setFaceCulling (boolshouldCull)\fC [inline]\fP"
Set a boolean flag to determine if the current renderer should cull polygon faces or not\&.
.PP
\fBParameters:\fP
.RS 4
\fIshouldCull\fP A boolean flag that determines whether the renderer should cull rendered polygon faces or not\&. 
.RE
.PP

.PP
Definition at line 32 of file renderer_impl\&.h\&.
.SS "void ls::draw::renderer::setViewport (const math::vec2i &pos, const math::vec2i &size)\fC [inline]\fP"
Set the size of the active viewport within the currently bound framebuffer\&.
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP The lower-left hand cornet of the active framebuffer\&.
.br
\fIsize\fP The width and height of the desired viewport\&. 
.RE
.PP

.PP
Definition at line 8 of file renderer_impl\&.h\&.
.SS "void ls::draw::renderer::setWindingOrder (\fBwinding_order_t\fPwo)\fC [inline]\fP"
Set the winding order for all rendered polygons\&.
.PP
\fBParameters:\fP
.RS 4
\fIwo\fP An enumeration of winding_order_t, indicating whether polygons are to be rendered with their front faces as clockwise or counter- clockwise\&. 
.RE
.PP

.PP
Definition at line 15 of file renderer_impl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
