.TH "ls::draw::glyph" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::glyph \- 
.PP
Font Metrics\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fontResource\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~glyph\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "math::vec2i \fBsize\fP = {0}"
.br
.ti -1c
.RI "math::vec2i \fBadvance\fP = {0}"
.br
.ti -1c
.RI "math::vec2i \fBbearing\fP = {0}"
.br
.ti -1c
.RI "char * \fBpData\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Font Metrics\&. 


.PP
 
.SS "This contains the basic data for each individual glyph in a font\&. "

.PP
Definition at line 29 of file fontResource\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ls::draw::glyph::~glyph ()\fC [inline]\fP"

.PP
Definition at line 35 of file fontResource\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "math::vec2i ls::draw::glyph::advance = {0}"

.PP
Definition at line 31 of file fontResource\&.h\&.
.SS "math::vec2i ls::draw::glyph::bearing = {0}"

.PP
Definition at line 32 of file fontResource\&.h\&.
.SS "char* ls::draw::glyph::pData = nullptr"

.PP
Definition at line 33 of file fontResource\&.h\&.
.SS "math::vec2i ls::draw::glyph::size = {0}"

.PP
Definition at line 30 of file fontResource\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
