.TH "ls::draw::vertex" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::vertex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "math::vec3 \fBpos\fP"
.br
.ti -1c
.RI "math::vec2 \fBuv\fP"
.br
.ti -1c
.RI "math::vec3 \fBnorm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic vertex building block in LS\&. This vertex type contains enough information to light a textured mesh\&. 
.PP
Definition at line 26 of file vertex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "math::vec3 ls::draw::vertex::norm"

.PP
Definition at line 29 of file vertex\&.h\&.
.SS "math::vec3 ls::draw::vertex::pos"

.PP
Definition at line 27 of file vertex\&.h\&.
.SS "math::vec2 ls::draw::vertex::uv"

.PP
Definition at line 28 of file vertex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
