.TH "ls::draw::sceneManager" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::sceneManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sceneManager\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : unsigned { \fBINVALID_SCENE_ID\fP = ((unsigned)-1) }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsceneManager\fP ()"
.br
.ti -1c
.RI "\fBsceneManager\fP (const \fBsceneManager\fP &)=delete"
.br
.ti -1c
.RI "\fBsceneManager\fP (\fBsceneManager\fP &&)"
.br
.ti -1c
.RI "\fB~sceneManager\fP ()"
.br
.ti -1c
.RI "\fBsceneManager\fP & \fBoperator=\fP (const \fBsceneManager\fP &)=delete"
.br
.ti -1c
.RI "\fBsceneManager\fP & \fBoperator=\fP (\fBsceneManager\fP &&)"
.br
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBterminate\fP ()"
.br
.ti -1c
.RI "const \fBtexture\fP & \fBgetDefaultTexture\fP () const "
.br
.ti -1c
.RI "\fBmeshList\fP & \fBgetMeshList\fP ()"
.br
.ti -1c
.RI "\fBtextureList\fP & \fBgetTextureList\fP ()"
.br
.ti -1c
.RI "\fBatlasList\fP & \fBgetAtlasList\fP ()"
.br
.ti -1c
.RI "\fBdrawList\fP & \fBgetModelList\fP ()"
.br
.ti -1c
.RI "const \fBmeshList\fP & \fBgetMeshList\fP () const "
.br
.ti -1c
.RI "const \fBtextureList\fP & \fBgetTextureList\fP () const "
.br
.ti -1c
.RI "const \fBatlasList\fP & \fBgetAtlasList\fP () const "
.br
.ti -1c
.RI "const \fBdrawList\fP & \fBgetModelList\fP () const "
.br
.ti -1c
.RI "\fBmesh\fP * \fBgetMesh\fP (unsigned index) const "
.br
.ti -1c
.RI "\fBtexture\fP * \fBgetTexture\fP (unsigned index) const "
.br
.ti -1c
.RI "\fBatlas\fP * \fBgetAtlas\fP (unsigned index) const "
.br
.ti -1c
.RI "\fBmeshModel\fP * \fBgetModel\fP (unsigned index) const "
.br
.ti -1c
.RI "void \fBeraseMesh\fP (unsigned index)"
.br
.ti -1c
.RI "void \fBeraseTexture\fP (unsigned index)"
.br
.ti -1c
.RI "void \fBeraseAtlas\fP (unsigned index)"
.br
.ti -1c
.RI "void \fBeraseModel\fP (unsigned index)"
.br
.ti -1c
.RI "unsigned \fBgetNumMeshes\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumTextures\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumAtlases\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumModels\fP () const "
.br
.ti -1c
.RI "unsigned \fBmanageMesh\fP (\fBmesh\fP *const)"
.br
.ti -1c
.RI "unsigned \fBmanageTexture\fP (\fBtexture\fP *const)"
.br
.ti -1c
.RI "unsigned \fBmanageAtlas\fP (\fBatlas\fP *const)"
.br
.ti -1c
.RI "unsigned \fBmanageModel\fP (\fBmeshModel\fP *const)"
.br
.ti -1c
.RI "\fBmesh\fP * \fBunManageMesh\fP (unsigned index)"
.br
.ti -1c
.RI "\fBtexture\fP * \fBunManageTexture\fP (unsigned index)"
.br
.ti -1c
.RI "\fBatlas\fP * \fBunManageAtlas\fP (unsigned index)"
.br
.ti -1c
.RI "\fBmeshModel\fP * \fBunManageModel\fP (unsigned index)"
.br
.ti -1c
.RI "bool \fBcontainsMesh\fP (const \fBmesh\fP *const) const "
.br
.ti -1c
.RI "bool \fBcontainsTexture\fP (const \fBtexture\fP *const) const "
.br
.ti -1c
.RI "bool \fBcontainsAtlas\fP (const \fBatlas\fP *const) const "
.br
.ti -1c
.RI "bool \fBcontainsModel\fP (const \fBmeshModel\fP *const) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
 Scene manager class
.PP
Contains all visual elements to a scene such as meshes, textures, texture 
.SS "atlases, shaders, etc\&. "

.PP
Definition at line 45 of file sceneManager\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum : unsigned"
Enums for types needed by the scene manager\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINVALID_SCENE_ID \fP\fP
.PP
Definition at line 50 of file sceneManager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ls::draw::sceneManager::sceneManager ()"

.PP
Definition at line 34 of file sceneManager\&.cpp\&.
.SS "ls::draw::sceneManager::sceneManager (const \fBsceneManager\fP &)\fC [delete]\fP"

.SS "ls::draw::sceneManager::sceneManager (\fBsceneManager\fP &&sm)"

.PP
Definition at line 45 of file sceneManager\&.cpp\&.
.SS "ls::draw::sceneManager::~sceneManager ()"

.PP
Definition at line 27 of file sceneManager\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ls::draw::sceneManager::containsAtlas (const \fBatlas\fP * constpAtlas) const"

.PP
Definition at line 369 of file sceneManager\&.cpp\&.
.SS "bool ls::draw::sceneManager::containsMesh (const \fBmesh\fP * constpMesh) const"

.PP
Definition at line 333 of file sceneManager\&.cpp\&.
.SS "bool ls::draw::sceneManager::containsModel (const \fBmeshModel\fP * constpText) const"

.PP
Definition at line 387 of file sceneManager\&.cpp\&.
.SS "bool ls::draw::sceneManager::containsTexture (const \fBtexture\fP * constpTex) const"

.PP
Definition at line 351 of file sceneManager\&.cpp\&.
.SS "void ls::draw::sceneManager::eraseAtlas (unsignedindex)"

.PP
Definition at line 225 of file sceneManager\&.cpp\&.
.SS "void ls::draw::sceneManager::eraseMesh (unsignedindex)"

.PP
Definition at line 213 of file sceneManager\&.cpp\&.
.SS "void ls::draw::sceneManager::eraseModel (unsignedindex)"

.PP
Definition at line 231 of file sceneManager\&.cpp\&.
.SS "void ls::draw::sceneManager::eraseTexture (unsignedindex)"

.PP
Definition at line 219 of file sceneManager\&.cpp\&.
.SS "\fBatlas\fP * ls::draw::sceneManager::getAtlas (unsignedindex) const"

.PP
Definition at line 200 of file sceneManager\&.cpp\&.
.SS "\fBatlasList\fP & ls::draw::sceneManager::getAtlasList ()"

.PP
Definition at line 160 of file sceneManager\&.cpp\&.
.SS "const \fBatlasList\fP & ls::draw::sceneManager::getAtlasList () const"

.PP
Definition at line 179 of file sceneManager\&.cpp\&.
.SS "const \fBtexture\fP & ls::draw::sceneManager::getDefaultTexture () const\fC [inline]\fP"
Get the default texture used by freshly loaded models\&.
.PP
\fBReturns:\fP
.RS 4
A constant reference to the default model texture 
.RE
.PP

.PP
Definition at line 8 of file sceneManager_impl\&.h\&.
.SS "\fBmesh\fP * ls::draw::sceneManager::getMesh (unsignedindex) const"

.PP
Definition at line 190 of file sceneManager\&.cpp\&.
.SS "\fBmeshList\fP & ls::draw::sceneManager::getMeshList ()"

.PP
Definition at line 152 of file sceneManager\&.cpp\&.
.SS "const \fBmeshList\fP & ls::draw::sceneManager::getMeshList () const"

.PP
Definition at line 171 of file sceneManager\&.cpp\&.
.SS "\fBmeshModel\fP * ls::draw::sceneManager::getModel (unsignedindex) const"

.PP
Definition at line 205 of file sceneManager\&.cpp\&.
.SS "\fBdrawList\fP & ls::draw::sceneManager::getModelList ()"

.PP
Definition at line 164 of file sceneManager\&.cpp\&.
.SS "const \fBdrawList\fP & ls::draw::sceneManager::getModelList () const"

.PP
Definition at line 183 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::getNumAtlases () const"

.PP
Definition at line 248 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::getNumMeshes () const"

.PP
Definition at line 240 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::getNumModels () const"

.PP
Definition at line 252 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::getNumTextures () const"

.PP
Definition at line 244 of file sceneManager\&.cpp\&.
.SS "\fBtexture\fP * ls::draw::sceneManager::getTexture (unsignedindex) const"

.PP
Definition at line 195 of file sceneManager\&.cpp\&.
.SS "\fBtextureList\fP & ls::draw::sceneManager::getTextureList ()"

.PP
Definition at line 156 of file sceneManager\&.cpp\&.
.SS "const \fBtextureList\fP & ls::draw::sceneManager::getTextureList () const"

.PP
Definition at line 175 of file sceneManager\&.cpp\&.
.SS "bool ls::draw::sceneManager::init ()"

.PP
Definition at line 69 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::manageAtlas (\fBatlas\fP * constpAtlas)"

.PP
Definition at line 279 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::manageMesh (\fBmesh\fP * constpMesh)"

.PP
Definition at line 259 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::manageModel (\fBmeshModel\fP * constpText)"

.PP
Definition at line 289 of file sceneManager\&.cpp\&.
.SS "unsigned ls::draw::sceneManager::manageTexture (\fBtexture\fP * constpTexture)"

.PP
Definition at line 269 of file sceneManager\&.cpp\&.
.SS "\fBsceneManager\fP& ls::draw::sceneManager::operator= (const \fBsceneManager\fP &)\fC [delete]\fP"

.SS "\fBsceneManager\fP & ls::draw::sceneManager::operator= (\fBsceneManager\fP &&sm)"

.PP
Definition at line 56 of file sceneManager\&.cpp\&.
.SS "void ls::draw::sceneManager::terminate ()"

.PP
Definition at line 86 of file sceneManager\&.cpp\&.
.SS "\fBatlas\fP * ls::draw::sceneManager::unManageAtlas (unsignedindex)"

.PP
Definition at line 316 of file sceneManager\&.cpp\&.
.SS "\fBmesh\fP * ls::draw::sceneManager::unManageMesh (unsignedindex)"

.PP
Definition at line 302 of file sceneManager\&.cpp\&.
.SS "\fBmeshModel\fP * ls::draw::sceneManager::unManageModel (unsignedindex)"

.PP
Definition at line 323 of file sceneManager\&.cpp\&.
.SS "\fBtexture\fP * ls::draw::sceneManager::unManageTexture (unsignedindex)"

.PP
Definition at line 309 of file sceneManager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
