.TH "ls::draw::atlas" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::draw::atlas \- 
.PP
Texture Atlas Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <atlas\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBatlas\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBatlas\fP (const \fBatlas\fP &)=delete"
.br
.RI "\fICopy constructor - DELETED\&. \fP"
.ti -1c
.RI "\fBatlas\fP (\fBatlas\fP &&a)"
.br
.RI "\fIMove Constructor\&. \fP"
.ti -1c
.RI "\fB~atlas\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "\fBatlas\fP & \fBoperator=\fP (const \fBatlas\fP &)=delete"
.br
.RI "\fICopy Operator - DELETED\&. \fP"
.ti -1c
.RI "\fBatlas\fP & \fBoperator=\fP (\fBatlas\fP &&a)"
.br
.RI "\fIMove operator\&. \fP"
.ti -1c
.RI "unsigned \fBgetId\fP () const "
.br
.ti -1c
.RI "bool \fBinit\fP (const \fBfontResource\fP &fr)"
.br
.ti -1c
.RI "void \fBterminate\fP ()"
.br
.ti -1c
.RI "const \fBtexture\fP & \fBgetTexture\fP () const "
.br
.ti -1c
.RI "\fBtexture\fP & \fBgetTexture\fP ()"
.br
.ti -1c
.RI "const \fBatlasEntry\fP & \fBgetEntry\fP (unsigned index) const "
.br
.ti -1c
.RI "const \fBatlasEntry\fP * \fBgetEntries\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetNumEntries\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Texture Atlas Class\&. 


.PP
 A texture atlas contains a collection of textures which may be loaded into 
.SS "GPU memory as a single texture\&. "

.PP
Definition at line 52 of file atlas\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ls::draw::atlas::atlas ()"

.PP
Constructor\&. 
.PP
Definition at line 29 of file atlas\&.cpp\&.
.SS "ls::draw::atlas::atlas (const \fBatlas\fP &)\fC [delete]\fP"

.PP
Copy constructor - DELETED\&. 
.SS "ls::draw::atlas::atlas (\fBatlas\fP &&a)"

.PP
Move Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP An r-value reference to a temporary atlas object\&.
.RE
.PP
Moves all data from the input parameter into *this\&. No copies are performed\&. 
.PP
Definition at line 35 of file atlas\&.cpp\&.
.SS "ls::draw::atlas::~atlas ()"

.PP
Destructor\&. Releases all data used by *this\&. 
.PP
Definition at line 22 of file atlas\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBatlasEntry\fP * ls::draw::atlas::getEntries () const\fC [inline]\fP"
Retrieve the array of atlas entries contained within *this\&.
.PP
\fBReturns:\fP
.RS 4
A constant pointer to the the internal array of atlas glyphs 
.RE
.PP

.PP
Definition at line 36 of file atlas_impl\&.h\&.
.SS "const \fBatlasEntry\fP & ls::draw::atlas::getEntry (unsignedindex) const\fC [inline]\fP"
Retrieve the atlas entry specified by at a specific index\&. Make sure that the atlas has been loaded before calling this\&.
.PP
Depending on the font loaded, this function will correspond to either ASCII codes of UTF codes
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP An unsigned integral type, representing the index of a desired glyph within *this object's glyph table\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A constant reference to a single glyph within the texture atlas\&. 
.RE
.PP

.PP
Definition at line 29 of file atlas_impl\&.h\&.
.SS "unsigned ls::draw::atlas::getId () const\fC [inline]\fP"
Get a runtime ID associated with this object
.PP
\fBReturns:\fP
.RS 4
The GPU-Assigned ID that is used by this object's internal texture atlas\&. 
.RE
.PP

.PP
Definition at line 8 of file atlas_impl\&.h\&.
.SS "unsigned ls::draw::atlas::getNumEntries () const\fC [inline]\fP"
Get the number of atlas entries currently loaded 
.PP
Definition at line 43 of file atlas_impl\&.h\&.
.SS "const \fBtexture\fP & ls::draw::atlas::getTexture () const\fC [inline]\fP"
Retrieve the texture rectangle used by *this\&.
.PP
\fBReturns:\fP
.RS 4
A constant reference to the internal texture used by *this\&. 
.RE
.PP

.PP
Definition at line 15 of file atlas_impl\&.h\&.
.SS "\fBtexture\fP & ls::draw::atlas::getTexture ()\fC [inline]\fP"
Get the texture object associated with *this
.PP
\fBReturns:\fP
.RS 4
A reference to the internal texture used by *this\&. 
.RE
.PP

.PP
Definition at line 22 of file atlas_impl\&.h\&.
.SS "bool ls::draw::atlas::init (const \fBfontResource\fP &fr)"
Stores the bitmap data located within a font file in *this as a texture atlas\&.
.PP
\fBParameters:\fP
.RS 4
\fIfr\fP A fully loaded font file
.RE
.PP
\fBReturns:\fP
.RS 4
True if the data was sent to OpenGL\&. False if an error occurred\&. 
.RE
.PP

.PP
Definition at line 62 of file atlas\&.cpp\&.
.SS "\fBatlas\fP& ls::draw::atlas::operator= (const \fBatlas\fP &)\fC [delete]\fP"

.PP
Copy Operator - DELETED\&. 
.SS "\fBatlas\fP & ls::draw::atlas::operator= (\fBatlas\fP &&a)"

.PP
Move operator\&. Moves all data from the input parameter into *this\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP An r-value reference to a temporary atlas object\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A reference to *this 
.RE
.PP

.PP
Definition at line 47 of file atlas\&.cpp\&.
.SS "void ls::draw::atlas::terminate ()"
Frees all memory used by *this\&. 
.PP
Definition at line 154 of file atlas\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
