.TH "ls::game" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::game \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglobal\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgameState\fP"
.br
.RI "\fIGame State Base Class\&. \fP"
.ti -1c
.RI "class \fBmanager\fP"
.br
.RI "\fIManager Object\&. \fP"
.ti -1c
.RI "class \fBsystem\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgame_state_t\fP : unsigned { \fBLS_GAME_INVALID\fP = (unsigned)-1, \fBLS_GAME_PAUSED\fP = 0, \fBLS_GAME_RUNNING\fP = 1, \fBLS_GAME_STOPPED\fP = 2, \fBLS_GAME_INIT\fP = 3 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBls::game::game_state_t\fP : unsigned"

.PP
 A game_state_t is a type used in order to help manage interactions between 
.SS "\fBls::game::system\fP objects and different game state objects\&. "

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILS_GAME_INVALID \fP\fP
.TP
\fB\fILS_GAME_PAUSED \fP\fP
.TP
\fB\fILS_GAME_RUNNING \fP\fP
.TP
\fB\fILS_GAME_STOPPED \fP\fP
.TP
\fB\fILS_GAME_INIT \fP\fP
.PP
Definition at line 38 of file gameState\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
