.TH "ls::game::global" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::game::global \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "\fILightSky Initialization\&. \fP"
.ti -1c
.RI "void \fBterminate\fP ()"
.br
.RI "\fILightSky termination\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool ls::game::global::init ()"

.PP
LightSky Initialization\&. 
.PP
\fBReturns:\fP
.RS 4
TRUE if the framework was able to initialize properly, or FALSE if not\&. 
.RE
.PP

.PP
Definition at line 18 of file game\&.cpp\&.
.SS "void ls::game::global::terminate ()"

.PP
LightSky termination\&. Frees all extra resources used by the framework\&. 
.PP
Definition at line 64 of file game\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
