.TH "ls::math::mat2_t< num_t >" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::math::mat2_t< num_t > \- 
.PP
2D Matrix Structure recommended for use with non-integral types  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBmat2_t\fP (num_t inXX, num_t inXY, num_t inYX, num_t inYY)"
.br
.ti -1c
.RI "constexpr \fBmat2_t\fP ()"
.br
.ti -1c
.RI "constexpr \fBmat2_t\fP (num_t)"
.br
.ti -1c
.RI "constexpr \fBmat2_t\fP (const \fBmat2_t\fP< num_t > &)"
.br
.ti -1c
.RI "constexpr \fBmat2_t\fP (\fBmat2_t\fP< num_t > &&)"
.br
.ti -1c
.RI "constexpr \fBmat2_t\fP (const \fBvec2_t\fP< num_t > &x, const \fBvec2_t\fP< num_t > &y)"
.br
.ti -1c
.RI "\fB~mat2_t\fP ()=default"
.br
.ti -1c
.RI "template<typename other_t > constexpr \fBoperator mat2_t< other_t >\fP () const "
.br
.ti -1c
.RI "const \fBvec2_t\fP< num_t > & \fBoperator[]\fP (int i) const "
.br
.ti -1c
.RI "\fBvec2_t\fP< num_t > & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator--\fP (int)"
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator+\fP (const \fBmat2_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator-\fP (const \fBmat2_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator-\fP () const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator*\fP (const \fBmat2_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator=\fP (const \fBmat2_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator=\fP (\fBmat2_t\fP< num_t > &&input)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator+=\fP (const \fBmat2_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator-=\fP (const \fBmat2_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator*=\fP (const \fBmat2_t\fP< num_t > &input)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBmat2_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBmat2_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator+\fP (const \fBvec2_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator-\fP (const \fBvec2_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBvec2_t\fP< num_t > \fBoperator*\fP (const \fBvec2_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator=\fP (const \fBvec2_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator+=\fP (const \fBvec2_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator-=\fP (const \fBvec2_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator+\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator-\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator*\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat2_t\fP \fBoperator/\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator+=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator-=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator*=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat2_t\fP & \fBoperator/=\fP (num_t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvec2_t\fP< num_t > \fBm\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename num_t>struct ls::math::mat2_t< num_t >"
2D Matrix Structure recommended for use with non-integral types 


.PP
 
.PP
\fBNote:\fP
.RS 4
Matrix is Row-Major Orientation is as follows: 0[0-1] = XX XY 
.SS "1[0-1] = YX YY "
.RE
.PP

.PP
Definition at line 23 of file mat2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename num_t > constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP (num_tinXX, num_tinXY, num_tinYX, num_tinYY)"

.PP
Definition at line 10 of file mat2_impl\&.h\&.
.SS "template<typename num_t> constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP ()"

.SS "template<typename num_t> constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP (num_t)"

.SS "template<typename num_t> constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP (const \fBmat2_t\fP< num_t > &)"

.SS "template<typename num_t> constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP (\fBmat2_t\fP< num_t > &&)"

.SS "template<typename num_t> constexpr \fBls::math::mat2_t\fP< num_t >::\fBmat2_t\fP (const \fBvec2_t\fP< num_t > &x, const \fBvec2_t\fP< num_t > &y)"

.SS "template<typename num_t> \fBls::math::mat2_t\fP< num_t >::~\fBmat2_t\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename num_t> template<typename other_t > constexpr \fBls::math::mat2_t\fP< num_t >::operator \fBmat2_t\fP< other_t > () const\fC [explicit]\fP"

.SS "template<typename num_t> bool \fBls::math::mat2_t\fP< num_t >::operator!= (const \fBmat2_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator* (const \fBmat2_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBvec2_t\fP<num_t> \fBls::math::mat2_t\fP< num_t >::operator* (const \fBvec2_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator* (num_t) const"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator*= (const \fBmat2_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator*= (num_t)"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator+ (const \fBmat2_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator+ (const \fBvec2_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator+ (num_t) const"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator++ ()"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator++ (int)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator+= (const \fBmat2_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator+= (const \fBvec2_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator+= (num_t)"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator- (const \fBmat2_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator- () const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator- (const \fBvec2_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator- (num_t) const"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator-- ()"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator-- (int)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator-= (const \fBmat2_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator-= (const \fBvec2_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator-= (num_t)"

.SS "template<typename num_t> \fBmat2_t\fP \fBls::math::mat2_t\fP< num_t >::operator/ (num_t) const"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator/= (num_t)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator= (const \fBmat2_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator= (\fBmat2_t\fP< num_t > &&input)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator= (const \fBvec2_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat2_t\fP& \fBls::math::mat2_t\fP< num_t >::operator= (num_t)"

.SS "template<typename num_t> bool \fBls::math::mat2_t\fP< num_t >::operator== (const \fBmat2_t\fP< num_t > &input) const"

.SS "template<typename num_t> const \fBvec2_t\fP<num_t>& \fBls::math::mat2_t\fP< num_t >::operator[] (inti) const\fC [inline]\fP"

.SS "template<typename num_t> \fBvec2_t\fP<num_t>& \fBls::math::mat2_t\fP< num_t >::operator[] (inti)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename num_t> \fBvec2_t\fP<num_t> \fBls::math::mat2_t\fP< num_t >::m[2]"

.PP
Definition at line 25 of file mat2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
