.TH "ls::math::fixed_t< fixed_base_t, num_frac_digits >" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::math::fixed_t< fixed_base_t, num_frac_digits > \- 
.PP
Fixed-Point number Class\&. Utilizes the bits provided by a type from a 'fixed_base_t' in order to store integral values that represent a fixed-precision number\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fixed\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename fixed_base_t, unsigned num_frac_digits>class ls::math::fixed_t< fixed_base_t, num_frac_digits >"
Fixed-Point number Class\&. Utilizes the bits provided by a type from a 'fixed_base_t' in order to store integral values that represent a fixed-precision number\&. 


.PP
 
.SS "In it's current state, it's prone to overflows\&. "

.PP
Definition at line 23 of file fixed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
