.TH "ls::math::mat4_t< num_t >" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::math::mat4_t< num_t > \- 
.PP
4D Matrix Structure recommended for use with non-integral types  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat4\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBmat4_t\fP (num_t inXX, num_t inXY, num_t inXZ, num_t inXW, num_t inYX, num_t inYY, num_t inYZ, num_t inYW, num_t inZX, num_t inZY, num_t inZZ, num_t inZW, num_t inWX, num_t inWY, num_t inWZ, num_t inWW)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP ()"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (num_t)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (const \fBmat3_t\fP< num_t > &)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (const \fBmat4_t\fP< num_t > &)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (\fBmat3_t\fP< num_t > &&)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (\fBmat4_t\fP< num_t > &&)"
.br
.ti -1c
.RI "constexpr \fBmat4_t\fP (const \fBvec4_t\fP< num_t > &x, const \fBvec4_t\fP< num_t > &y, const \fBvec4_t\fP< num_t > &z, const \fBvec4_t\fP< num_t > &w)"
.br
.ti -1c
.RI "\fB~mat4_t\fP ()=default"
.br
.ti -1c
.RI "template<typename other_t > constexpr \fBoperator mat4_t< other_t >\fP () const "
.br
.ti -1c
.RI "const \fBvec4_t\fP< num_t > & \fBoperator[]\fP (int i) const "
.br
.ti -1c
.RI "\fBvec4_t\fP< num_t > & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator--\fP (int)"
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator+\fP (const \fBmat4_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator-\fP (const \fBmat4_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator-\fP () const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator*\fP (const \fBmat4_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator=\fP (const \fBmat4_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator=\fP (\fBmat4_t\fP< num_t > &&input)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator+=\fP (const \fBmat4_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator-=\fP (const \fBmat4_t\fP< num_t > &input)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator*=\fP (const \fBmat4_t\fP< num_t > &input)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBmat4_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBmat4_t\fP< num_t > &input) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator+\fP (const \fBvec4_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator-\fP (const \fBvec4_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBvec4_t\fP< num_t > \fBoperator*\fP (const \fBvec4_t\fP< num_t > &) const "
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator=\fP (const \fBvec4_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator+=\fP (const \fBvec4_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator-=\fP (const \fBvec4_t\fP< num_t > &)"
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator+\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator-\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator*\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat4_t\fP \fBoperator/\fP (num_t) const "
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator+=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator-=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator*=\fP (num_t)"
.br
.ti -1c
.RI "\fBmat4_t\fP & \fBoperator/=\fP (num_t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvec4_t\fP< num_t > \fBm\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename num_t>struct ls::math::mat4_t< num_t >"
4D Matrix Structure recommended for use with non-integral types 


.PP
 
.PP
\fBNote:\fP
.RS 4
Matrix is Row-Major Orientation is as follows: 0[0-3] = XX XY XZ XW 1[0-3] = YX YY YZ YW 2[0-3] = ZX ZY ZZ ZW 
.SS "3[0-3] = WX WY WZ WW "
.RE
.PP

.PP
Definition at line 25 of file mat4\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename num_t > constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (num_tinXX, num_tinXY, num_tinXZ, num_tinXW, num_tinYX, num_tinYY, num_tinYZ, num_tinYW, num_tinZX, num_tinZY, num_tinZZ, num_tinZW, num_tinWX, num_tinWY, num_tinWZ, num_tinWW)"

.PP
Definition at line 10 of file mat4_impl\&.h\&.
.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP ()"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (num_t)"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (const \fBmat3_t\fP< num_t > &)"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (const \fBmat4_t\fP< num_t > &)"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (\fBmat3_t\fP< num_t > &&)"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (\fBmat4_t\fP< num_t > &&)"

.SS "template<typename num_t> constexpr \fBls::math::mat4_t\fP< num_t >::\fBmat4_t\fP (const \fBvec4_t\fP< num_t > &x, const \fBvec4_t\fP< num_t > &y, const \fBvec4_t\fP< num_t > &z, const \fBvec4_t\fP< num_t > &w)"

.SS "template<typename num_t> \fBls::math::mat4_t\fP< num_t >::~\fBmat4_t\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename num_t> template<typename other_t > constexpr \fBls::math::mat4_t\fP< num_t >::operator \fBmat4_t\fP< other_t > () const\fC [explicit]\fP"

.SS "template<typename num_t> bool \fBls::math::mat4_t\fP< num_t >::operator!= (const \fBmat4_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator* (const \fBmat4_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBvec4_t\fP<num_t> \fBls::math::mat4_t\fP< num_t >::operator* (const \fBvec4_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator* (num_t) const"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator*= (const \fBmat4_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator*= (num_t)"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator+ (const \fBmat4_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator+ (const \fBvec4_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator+ (num_t) const"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator++ ()"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator++ (int)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator+= (const \fBmat4_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator+= (const \fBvec4_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator+= (num_t)"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator- (const \fBmat4_t\fP< num_t > &input) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator- () const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator- (const \fBvec4_t\fP< num_t > &) const"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator- (num_t) const"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator-- ()"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator-- (int)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator-= (const \fBmat4_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator-= (const \fBvec4_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator-= (num_t)"

.SS "template<typename num_t> \fBmat4_t\fP \fBls::math::mat4_t\fP< num_t >::operator/ (num_t) const"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator/= (num_t)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator= (const \fBmat4_t\fP< num_t > &input)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator= (\fBmat4_t\fP< num_t > &&input)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator= (const \fBvec4_t\fP< num_t > &)"

.SS "template<typename num_t> \fBmat4_t\fP& \fBls::math::mat4_t\fP< num_t >::operator= (num_t)"

.SS "template<typename num_t> bool \fBls::math::mat4_t\fP< num_t >::operator== (const \fBmat4_t\fP< num_t > &input) const"

.SS "template<typename num_t> const \fBvec4_t\fP<num_t>& \fBls::math::mat4_t\fP< num_t >::operator[] (inti) const\fC [inline]\fP"

.SS "template<typename num_t> \fBvec4_t\fP<num_t>& \fBls::math::mat4_t\fP< num_t >::operator[] (inti)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename num_t> \fBvec4_t\fP<num_t> \fBls::math::mat4_t\fP< num_t >::m[4]"

.PP
Definition at line 27 of file mat4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
