.TH "ls::script::variable" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls::script::variable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <variable\&.h>\fP
.PP
Inherits \fBls::script::scriptable\fP\&.
.PP
Inherited by \fBls::script::variable_t< hashId, type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~variable\fP ()=0"
.br
.ti -1c
.RI "\fBvariable\fP ()"
.br
.RI "\fIConstructor Constructs *this and the 'scriptable' base class\&. \fP"
.ti -1c
.RI "\fBvariable\fP (const \fBvariable\fP &v)"
.br
.RI "\fICopy Constructor Copies data from the input parameter into *this\&. \fP"
.ti -1c
.RI "\fBvariable\fP (\fBvariable\fP &&v)"
.br
.RI "\fIMove Constructor Moves data from the input parameter into *this without performing any copies\&. \fP"
.ti -1c
.RI "\fBvariable\fP & \fBoperator=\fP (const \fBvariable\fP &v)"
.br
.RI "\fICopy Constructor Copies data from the input parameter into *this\&. \fP"
.ti -1c
.RI "\fBvariable\fP & \fBoperator=\fP (\fBvariable\fP &&v)"
.br
.RI "\fIMove Operator Moves data from the input parameter into *this without performing any copies\&. \fP"
.ti -1c
.RI "\fBscript_base_t\fP \fBgetScriptType\fP () const final"
.br
.RI "\fIgetScriptType Retrieve the type of scripting object *this is\&. \fP"
.ti -1c
.RI "virtual hash_t \fBgetScriptSubType\fP () const =0"
.br
.RI "\fIgetScriptSubType Used to determine the run-time-type information about the type of scripting object that *this is\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
 Variable Base Type
.PP
.SS "The Variable base object is used as an interface for scriptable data types\&. "

.PP
Definition at line 25 of file variable\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ls::script::variable::~variable ()\fC [pure virtual]\fP"

.PP
Definition at line 19 of file variable\&.cpp\&.
.SS "ls::script::variable::variable ()"

.PP
Constructor Constructs *this and the 'scriptable' base class\&. 
.PP
Definition at line 25 of file variable\&.cpp\&.
.SS "ls::script::variable::variable (const \fBvariable\fP &v)"

.PP
Copy Constructor Copies data from the input parameter into *this\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP A constant reference to a variable base object\&. 
.RE
.PP

.PP
Definition at line 32 of file variable\&.cpp\&.
.SS "ls::script::variable::variable (\fBvariable\fP &&v)"

.PP
Move Constructor Moves data from the input parameter into *this without performing any copies\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP An r-value reference to a variable base object\&. 
.RE
.PP

.PP
Definition at line 39 of file variable\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual hash_t ls::script::variable::getScriptSubType () const\fC [pure virtual]\fP"

.PP
getScriptSubType Used to determine the run-time-type information about the type of scripting object that *this is\&. 
.PP
\fBReturns:\fP
.RS 4
hash_t A hash code that indicates the specific type of object that *this is at run-time\&. 
.RE
.PP

.PP
Implements \fBls::script::scriptable\fP\&.
.PP
Implemented in \fBls::script::variable_t< hashId, type >\fP\&.
.SS "\fBscript_base_t\fP ls::script::variable::getScriptType () const\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
getScriptType Retrieve the type of scripting object *this is\&. 
.PP
\fBReturns:\fP
.RS 4
\fBls::script::script_base_t::SCRIPT_VAR\fP 
.RE
.PP

.PP
Implements \fBls::script::scriptable\fP\&.
.PP
Definition at line 30 of file variable_impl\&.h\&.
.SS "\fBvariable\fP & ls::script::variable::operator= (const \fBvariable\fP &v)\fC [inline]\fP"

.PP
Copy Constructor Copies data from the input parameter into *this\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP A constant reference to a variable base object\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A reference to *this\&. 
.RE
.PP

.PP
Definition at line 12 of file variable_impl\&.h\&.
.SS "\fBvariable\fP & ls::script::variable::operator= (\fBvariable\fP &&v)\fC [inline]\fP"

.PP
Move Operator Moves data from the input parameter into *this without performing any copies\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP An r-value reference to a variable base object\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A reference to *this\&. 
.RE
.PP

.PP
Definition at line 21 of file variable_impl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
