.TH "C:/Users/miles/C++/projects/LightSky/lightsky/game/manager.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/game/manager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include 'lightsky/game/generic/manager_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::game::manager< hash_t, data_t >\fP"
.br
.RI "\fIManager Object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::game\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
