.TH "C:/Users/miles/C++/projects/LightSky/lightsky/math/mat3.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/math/mat3.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/math/scalar_utils\&.h'\fP
.br
\fC#include 'lightsky/math/fixed\&.h'\fP
.br
\fC#include 'lightsky/math/vec3\&.h'\fP
.br
\fC#include 'lightsky/math/generic/mat3_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBls::math::mat3_t< num_t >\fP"
.br
.RI "\fI3D Matrix Structure recommended for use with non-integral types \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::math\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename num_t > mat3_t< num_t > \fBls::math::operator+\fP (num_t n, const mat3_t< num_t > &m)"
.br
.ti -1c
.RI "template<typename num_t > mat3_t< num_t > \fBls::math::operator-\fP (num_t n, const mat3_t< num_t > &m)"
.br
.ti -1c
.RI "template<typename num_t > mat3_t< num_t > \fBls::math::operator*\fP (num_t n, const mat3_t< num_t > &m)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3f, mat3_t, float)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3d, mat3_t, double)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3i, mat3_t, int)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3ui, mat3_t, unsigned)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3x, mat3_t, medp_t)"
.br
.ti -1c
.RI "\fBls::math::LS_DECLARE_CLASS_TYPE\fP (mat3, mat3_t, \fBLS_FLOAT\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
