.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/matrixStack.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/matrixStack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stack>\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/matrixStack_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::matrixStack\fP"
.br
.RI "\fIMatrix Stack\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::matrix_use_t\fP : unsigned { \fBls::draw::MATRIX_USE_INVALID\fP = (unsigned)-1, \fBls::draw::MATRIX_USE_PROJECTION\fP = 0, \fBls::draw::MATRIX_USE_VIEW\fP = 1, \fBls::draw::MATRIX_USE_MODEL\fP = 2, \fBls::draw::MATRIX_USE_MAX\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
