.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/mesh.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/mesh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/atlas\&.h'\fP
.br
\fC#include 'lightsky/draw/boundingBox\&.h'\fP
.br
\fC#include 'lightsky/draw/bufferObject\&.h'\fP
.br
\fC#include 'lightsky/draw/renderer\&.h'\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/vertex\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/mesh_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::mesh\fP"
.br
.RI "\fIMesh Object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::mesh_property_t\fP : int { \fBls::draw::MESH_VERTS_PER_GLYPH\fP = 6, \fBls::draw::MESH_SPACES_PER_TAB\fP = 4 }"
.br
.RI "\fIMesh Properties\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
