.TH "C:/Users/miles/C++/projects/LightSky/lightsky/script/script.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/script/script.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/script/setup\&.h'\fP
.br
\fC#include 'lightsky/script/scriptable\&.h'\fP
.br
\fC#include 'lightsky/script/variable\&.h'\fP
.br
\fC#include 'lightsky/script/functor\&.h'\fP
.br
\fC#include 'lightsky/script/factory\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
