.TH "C:/Users/miles/C++/projects/LightSky/lightsky/script/scriptable.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/script/scriptable.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'lightsky/utils/hash\&.h'\fP
.br
\fC#include 'lightsky/script/setup\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::script::scriptable\fP"
.br
.RI "\fIScript Object Base Class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::script\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
