.TH "C:/Users/miles/C++/projects/LightSky/lightsky/setup/src/setup.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/setup/src/setup.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/setup/setup\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
