.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/src/shaderObject.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/src/shaderObject.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/shaderObject\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBls::draw::LS_DEFINE_CLASS_TYPE\fP (shaderObject, SHADER_STAGE_VERTEX)"
.br
.ti -1c
.RI "\fBls::draw::LS_DEFINE_CLASS_TYPE\fP (shaderObject, SHADER_STAGE_GEOMETRY)"
.br
.ti -1c
.RI "\fBls::draw::LS_DEFINE_CLASS_TYPE\fP (shaderObject, SHADER_STAGE_FRAGMENT)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
