.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/string_utils.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/string_utils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'lightsky/utils/generic/string_utils_impl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::string \fBls::utils::toString\fP (const T &data)"
.br
.RI "\fIConvert a basic data type to an std::string\&. \fP"
.ti -1c
.RI "std::string \fBls::utils::convertWtoMb\fP (const std::wstring &wstr)"
.br
.RI "\fIConvert a Wide String to a Multi-Byte Character String\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
