.TH "C:/Users/miles/C++/projects/LightSky/lightsky/game/system.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/game/system.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'lightsky/draw/context\&.h'\fP
.br
\fC#include 'lightsky/draw/display\&.h'\fP
.br
\fC#include 'lightsky/utils/randomNum\&.h'\fP
.br
\fC#include 'lightsky/game/setup\&.h'\fP
.br
\fC#include 'lightsky/game/generic/system_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::game::system\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::game\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
