.TH "C:/Users/miles/C++/projects/LightSky/lightsky/game/src/system.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/game/src/system.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <new>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_timer\&.h>\fP
.br
\fC#include 'lightsky/game/gameState\&.h'\fP
.br
\fC#include 'lightsky/game/system\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::game\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
