.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/texture.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/texture.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'lightsky/draw/color\&.h'\fP
.br
\fC#include 'lightsky/draw/imageResource\&.h'\fP
.br
\fC#include 'lightsky/draw/setup\&.h'\fP
.br
\fC#include 'lightsky/draw/generic/texture_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::draw::texture\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::ls_tex_param_t\fP : int { \fBls::draw::LS_TEX_INVALID\fP = -1, \fBls::draw::LS_TEX_WIDTH\fP = GL_TEXTURE_WIDTH, \fBls::draw::LS_TEX_HEIGHT\fP = GL_TEXTURE_HEIGHT, \fBls::draw::LS_TEX_DEPTH\fP = GL_TEXTURE_DEPTH, \fBls::draw::LS_TEX_MIN_FILTER\fP = GL_TEXTURE_MIN_FILTER, \fBls::draw::LS_TEX_MAG_FILTER\fP = GL_TEXTURE_MAG_FILTER, \fBls::draw::LS_TEX_WRAP_S\fP = GL_TEXTURE_WRAP_S, \fBls::draw::LS_TEX_WRAP_T\fP = GL_TEXTURE_WRAP_T, \fBls::draw::LS_TEX_WRAP_R\fP = GL_TEXTURE_WRAP_R, \fBls::draw::LS_TEX_CLAMP_EDGE\fP = GL_CLAMP_TO_EDGE, \fBls::draw::LS_TEX_CLAMP_BORDER\fP = GL_CLAMP_TO_BORDER, \fBls::draw::LS_TEX_REPEAT\fP = GL_REPEAT }"
.br
.ti -1c
.RI "enum \fBls::draw::ls_tex_filter_t\fP : int { \fBls::draw::LS_FILTER_LINEAR\fP = GL_LINEAR, \fBls::draw::LS_FILTER_NEAREST\fP = GL_NEAREST, \fBls::draw::LS_FILTER_LINEAR_NEAREST\fP = GL_LINEAR_MIPMAP_NEAREST, \fBls::draw::LS_FILTER_NEAREST_NEAREST\fP = GL_NEAREST_MIPMAP_NEAREST, \fBls::draw::LS_FILTER_LINEAR_LINEAR\fP = GL_LINEAR_MIPMAP_LINEAR, \fBls::draw::LS_FILTER_NEAREST_LINEAR\fP = GL_NEAREST_MIPMAP_LINEAR }"
.br
.ti -1c
.RI "enum \fBls::draw::ls_tex_desc_t\fP : int { \fBls::draw::LS_TEX_1D\fP = GL_TEXTURE_1D, \fBls::draw::LS_TEX_2D\fP = GL_TEXTURE_2D, \fBls::draw::LS_TEX_3D\fP = GL_TEXTURE_3D, \fBls::draw::LS_TEX_RECT\fP = GL_TEXTURE_RECTANGLE }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
