.TH "C:/Users/miles/C++/projects/LightSky/lightsky/utils/tuple.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/utils/tuple.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <new>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'lightsky/utils/byteSize\&.h'\fP
.br
\fC#include 'lightsky/utils/generic/tuple_impl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBls::utils::tuple_t< data_t >\fP"
.br
.RI "\fITuple Class An tuple is a set of objects determined at compile-time\&. These objects are constructed within a tightly packed buffer\&. It is recommended to construct an tuple using the 'new' operator if there are many objects\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
