.TH "C:/Users/miles/C++/projects/LightSky/lightsky/math/types.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/math/types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <cstdint>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLS_FLOAT\fP   float"
.br
.ti -1c
.RI "#define \fBLS_INT\fP   int32_t"
.br
.ti -1c
.RI "#define \fBLS_UINT\fP   uint32_t"
.br
.ti -1c
.RI "#define \fBLS_ROUND\fP(x)   (std::floor(0\&.5f + x))"
.br
.ti -1c
.RI "#define \fBLS_DEG2RAD\fP(x)   (x * 0\&.01745329251994329577f)"
.br
.ti -1c
.RI "#define \fBLS_RAD2DEG\fP(x)   (x * 57\&.2957795130823208768f)"
.br
.ti -1c
.RI "#define \fBLS_PI\fP   3\&.14159265358979323846f"
.br
.ti -1c
.RI "#define \fBLS_TWO_PI\fP   6\&.28318530717958647693f"
.br
.ti -1c
.RI "#define \fBLS_PI_OVER_2\fP   1\&.57079632679489661923f"
.br
.ti -1c
.RI "#define \fBLS_PI_OVER_3\fP   1\&.04719755119659774615f"
.br
.ti -1c
.RI "#define \fBLS_PI_OVER_4\fP   0\&.78539816339744830962f"
.br
.ti -1c
.RI "#define \fBLS_PI_OVER_6\fP   0\&.52359877559829887307f"
.br
.ti -1c
.RI "#define \fBLS_PI_INVERSE\fP   0\&.31830988618379067153f"
.br
.ti -1c
.RI "#define \fBLS_E\fP   2\&.71828182845904523536f"
.br
.ti -1c
.RI "#define \fBLS_EPSILON\fP   1\&.0e-6f"
.br
.ti -1c
.RI "#define \fBLS_SIN\fP(x)   sinf(x)"
.br
.ti -1c
.RI "#define \fBLS_COS\fP(x)   cosf(x)"
.br
.ti -1c
.RI "#define \fBLS_TAN\fP(x)   tanf(x)"
.br
.ti -1c
.RI "#define \fBLS_SQRT\fP(x)   sqrtf(x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LS_COS(x)   cosf(x)"

.PP
Definition at line 63 of file types\&.h\&.
.SS "#define LS_DEG2RAD(x)   (x * 0\&.01745329251994329577f)"

.PP
Definition at line 49 of file types\&.h\&.
.SS "#define LS_E   2\&.71828182845904523536f"

.PP
Definition at line 59 of file types\&.h\&.
.SS "#define LS_EPSILON   1\&.0e-6f"

.PP
Definition at line 60 of file types\&.h\&.
.SS "#define LS_FLOAT   float"

.PP
Definition at line 44 of file types\&.h\&.
.SS "#define LS_INT   int32_t"

.PP
Definition at line 45 of file types\&.h\&.
.SS "#define LS_PI   3\&.14159265358979323846f"

.PP
Definition at line 52 of file types\&.h\&.
.SS "#define LS_PI_INVERSE   0\&.31830988618379067153f"

.PP
Definition at line 58 of file types\&.h\&.
.SS "#define LS_PI_OVER_2   1\&.57079632679489661923f"

.PP
Definition at line 54 of file types\&.h\&.
.SS "#define LS_PI_OVER_3   1\&.04719755119659774615f"

.PP
Definition at line 55 of file types\&.h\&.
.SS "#define LS_PI_OVER_4   0\&.78539816339744830962f"

.PP
Definition at line 56 of file types\&.h\&.
.SS "#define LS_PI_OVER_6   0\&.52359877559829887307f"

.PP
Definition at line 57 of file types\&.h\&.
.SS "#define LS_RAD2DEG(x)   (x * 57\&.2957795130823208768f)"

.PP
Definition at line 50 of file types\&.h\&.
.SS "#define LS_ROUND(x)   (std::floor(0\&.5f + x))"

.PP
Definition at line 48 of file types\&.h\&.
.SS "#define LS_SIN(x)   sinf(x)"

.PP
Definition at line 62 of file types\&.h\&.
.SS "#define LS_SQRT(x)   sqrtf(x)"

.PP
Definition at line 66 of file types\&.h\&.
.SS "#define LS_TAN(x)   tanf(x)"

.PP
Definition at line 64 of file types\&.h\&.
.SS "#define LS_TWO_PI   6\&.28318530717958647693f"

.PP
Definition at line 53 of file types\&.h\&.
.SS "#define LS_UINT   uint32_t"

.PP
Definition at line 46 of file types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
