.TH "C:/Users/miles/C++/projects/LightSky/lightsky/script/src/variable.cpp" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/script/src/variable.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/script/variable\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::script\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (char, char)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (short, short)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (int, int)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (long, long)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (float, float)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (double, double)"
.br
.ti -1c
.RI "\fBLS_SCRIPT_DEFINE_VAR\fP (string, std::string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LS_SCRIPT_DEFINE_VAR (char, char)"

.SS "LS_SCRIPT_DEFINE_VAR (short, short)"

.SS "LS_SCRIPT_DEFINE_VAR (int, int)"

.SS "LS_SCRIPT_DEFINE_VAR (long, long)"

.SS "LS_SCRIPT_DEFINE_VAR (float, float)"

.SS "LS_SCRIPT_DEFINE_VAR (double, double)"

.SS "LS_SCRIPT_DEFINE_VAR (string, std::string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
