.TH "C:/Users/miles/C++/projects/LightSky/lightsky/math/generic/vec4_impl.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/math/generic/vec4_impl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::math\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename num_t > vec4_t< num_t > \fBls::math::operator+\fP (num_t n, const vec4_t< num_t > &v)"
.br
.ti -1c
.RI "template<typename num_t > vec4_t< num_t > \fBls::math::operator-\fP (num_t n, const vec4_t< num_t > &v)"
.br
.ti -1c
.RI "template<typename num_t > vec4_t< num_t > \fBls::math::operator*\fP (num_t n, const vec4_t< num_t > &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
