.TH "C:/Users/miles/C++/projects/LightSky/lightsky/draw/vertex.h" 3 "Sun Oct 26 2014" "Version Pre-Alpha" "LightSky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/miles/C++/projects/LightSky/lightsky/draw/vertex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lightsky/draw/setup\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBls::draw::vertex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBls\fP"
.br
.ti -1c
.RI " \fBls::draw\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBls::draw::vertex_attrib_t\fP { \fBls::draw::VERTEX_ATTRIB_POS\fP = 0, \fBls::draw::VERTEX_ATTRIB_TEX\fP = 1, \fBls::draw::VERTEX_ATTRIB_NORM\fP = 2, \fBls::draw::VERTEX_ATTRIB_MAT_ROW\fP = 3, \fBls::draw::VERTEX_ATTRIB_MAT_ROW0\fP = 3, \fBls::draw::VERTEX_ATTRIB_MAT_ROW1\fP = 4, \fBls::draw::VERTEX_ATTRIB_MAT_ROW2\fP = 5, \fBls::draw::VERTEX_ATTRIB_MAT_ROW3\fP = 6 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LightSky from the source code\&.
